### ISSUE TITLE
Temporarily disable performance assessment dashboards

### ISSUE THREAD

**Issue by Mitchdoe** [AtlasOfLivingAustralia/fieldcapture#1008]
Due to changes in scores, the dashboard views should only be viewable by FC_ADMINs for the time being.
We'll then confirm all the reports in the system.

**Comment by chrisala** [comment]
Should the dashboards on the org page still be visible to FC_ADMINs or is the dashboard in the admin -> tools section sufficient?

**Comment by Mitchdoe** [comment]
Dashboard in Admin -> tools is sufficient, thanks.
