### ISSUE TITLE
Add common name to species scientific name display inside activity forms

### ISSUE THREAD

**Issue by Mitchdoe** [AtlasOfLivingAustralia/fieldcapture#1015]
E.g. in a pest management form, when you select Cervus elaphus, it should display "Red Deer" underneath.

**Comment by chrisala** [comment]
Is this referring to the popup when you hover over the 'i' icon or the actual text box?  A multi-line text box will probably cause issues, but I could do "scientific name (common name)" or "common name (scientific name)"?
