### ISSUE TITLE
New RLP project annual report

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#1761]

**Comment by NeilDoEE** [comment]
Hi Chris - Blaz and I have tested the Annual Project Report and to date have not been able to break it :) .  However, we were wondering if it is possible to add to question 3 ("Please outline which minimum annual target services have not been met and why") a drop-down listing the relevant Project services and minimum targets from the MERI plan (the 3rd last set of fields in the MERI plan)? If it's possible, it would be simpler for the Service Providers if the list could contain only the target services that are being delivered that year (ie where there is a value greater than 0 in the target column for the year being reported on).  Happy to discuss by phone if it is easier.
Cheers
Neil
