### ISSUE TITLE
Electorate boundaries to be updated

### ISSUE THREAD

**Issue by LizDoee** [AtlasOfLivingAustralia/fieldcapture#1822]

**Comment by qifeng-bai** [comment]
Code has been fixed, electorate in config needs to be updated after it is ready

**Comment by chrisala** [comment]
The new electoral boundary has been loaded into the ALA spatial portal and the configuration updated such that new requests to find electorates for a site will use the new layer.
Once this change is deployed to production, existing sites will have to be re-intersected against production as a batch process before the change will affect existing projects/sites.
