### ISSUE TITLE
ESP NA button

### ISSUE THREAD

**Issue by MadeleineDoEE** [AtlasOfLivingAustralia/fieldcapture#1920]
In ESP Annual Reporting form, each action/subheading has a button underneath "Not applicable". Please change the "Not applicable" text to read: Not an agreed management action under my funding agreement.

Functionality remains the same.

**Comment by chrisala** [comment]
On the instructions for the tables, could you please add some text – at the red x: If your situation makes it impractical to record your information in the table/rows below, please delete any row(s) from the table by clicking the X at the far right hand side.

**Comment by chrisala** [comment]
If Native Herbivore Management is a management action for the site but you didn’t undertake any actions around this for the reporting period, please complete the report and state why you didn’t, in the text box.
 
If Feral Animal Management is a management action for the site but you didn’t undertake any actions around this for the reporting period, please complete the report and state why you didn’t, in the text box.
 
If Weed Management is a management action for the site but you didn’t undertake any actions around this for the reporting period, please complete the report and state why you didn’t, in the text box.
 
If Biomass Control is a management action for the site but you didn’t undertake any actions around this for the reporting period, please complete the report and state why you didn’t, in the text box.
 
If Revegetation is a management action for the site but you didn’t undertake any actions around this for the reporting period, please complete the report and state why you didn’t, in the text box.
 
If Regeneration is a management action for the site but you didn’t undertake any actions around this for the reporting period, please complete the report and state why you didn’t, in the text box.
 
If Restoration of Habitat Features is a management action for the site but you didn’t undertake any actions around this for the reporting period, please complete the report and state why you didn’t, in the text box.
