### ISSUE TITLE
ESP PDFs (longer term)

### ISSUE THREAD

**Issue by MadeleineDoEE** [AtlasOfLivingAustralia/fieldcapture#1924]
Stewards need to be able to 
1. upon completion download a pdf of the report they've just written and 
2. download pdfs of previously submitted reports. 
Aware this will be a longer term task. Maybe one for the new year?

**Comment by chrisala** [comment]
* Add new tab "Download reports"
* On the tab, have a financial year / report selector and a button to generate a PDF.
