### ISSUE TITLE
Export program output data and filtered all data as CSV

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/fieldcapture#21]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=435
*date:* Tue Dec 10 05:01:40 2013
*author:* CoolDa...@gmail.com
 ---

Will need the ability to export both the program output data and all project data for a filtered selection of projects in a downloadable CSV format. 

Not required until Mar 2014.

**Comment by chrisala** [comment]
Done.
