### ISSUE TITLE
Add a new project status (Terminated)

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2160]
The new status should be "Terminated"
From a UI perspective it should behave the same as "Completed"

* Provide a pop-up to add an explanation of why the project was changed to "Terminated".

**Comment by thakuad** [comment]
https://upsource.ala.org.au/fieldcapture/review/FLDCP-CR-124

**Comment by thakuad** [comment]
https://github.com/AtlasOfLivingAustralia/ecodata/issues/644
