### ISSUE TITLE
If no "Other" org-type is entered, the read only view should display Other.

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2195]
To reproduce:
1) Go into a MERI plan that contains the "Project partnerships" section.
2) Select "Other" as the organisation type.
3) Leave the other organisation text field blank.
4) Save, then navigate to the MERI Plan tab.
5) View the PDF

Expected:
The organisation type on the MERI plan tab & PDF should display "Other" for the organisation type.

Actual:
The organisation type is blank.

**Comment by thakuad** [comment]
https://upsource.ala.org.au/fieldcapture/review/FLDCP-CR-141
