### ISSUE TITLE
JS Error in Read Only MERI Plan Tab

### ISSUE THREAD

**Issue by ghost** [AtlasOfLivingAustralia/fieldcapture#2250]
**Reproduce:** 
1. go to FDF program Projects. 
2. Unselect all FDF and NRM Outcomes
3. save changes

**Expectation:** 

No JS Error in console

**<img width="929" alt="Screen Shot 2021-05-17 at 11 47 27 am" src="https://user-images.githubusercontent.com/61674524/118422183-12524380-b706-11eb-9f65-1388174f1ac7.png">**

JS Error in Console

**Comment by thakuad** [comment]
https://github.com/AtlasOfLivingAustralia/fieldcapture/commit/49214bb5fdefff75fbc52c278da32f66d63f339e#diff-6411f666be527049850702820eeb693530be60de1cee5ecb5236459a2ffabeea
this changes in MeriPlan.js Line 1066 - 1069
This change was approved part of other review https://github.com/AtlasOfLivingAustralia/fieldcapture/issues/2213.
