### ISSUE TITLE
Unable to Edit/View/Download project Report by READ_ONLY USER for auditing purpose

### ISSUE THREAD

**Issue by ghost** [AtlasOfLivingAustralia/fieldcapture#2260]

**Comment by chrisala** [comment]
Currently, users with the FC_READ_ONLY role are unable to view reports.  They should be able to view & download reports.

**Comment by chrisala** [comment]
To reproduce:
1) Login as a user with the FC_READ_ONLY role.
2) Navigate to a project configured with a reporting tab (and which has finished reports). e.g. https://fieldcapture-test.ala.org.au/project/index/d69ee644-a46b-4848-9a1d-f10de6877bc4
3) Navigate to the Reporting tab, check the "Show all reports" checkbox.
4) Click the "eye" icon on a submitted/approved report.
5) Click the "download" icon on a submitted / approved report.

Expected results:
* In (4) the user should be presented with the read only view of the report.
* In (5) the user should be presented with ah PDF of the report

Actual results:
* The user is redirected back to the project and an error is displayed.
*

**Comment by chrisala** [comment]
This same problem applies to management unit reports, and is a bit worse as the user cannot even see the reporting tab.

**Comment by salomon-j** [comment]
https://upsource.ala.org.au/fieldcapture/review/FLDCP-CR-305
