### ISSUE TITLE
More broken MERI plan styling

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2359]
To reproduce: https://fieldcapture-test.ala.org.au/project/index/9f93d41b-7f6f-449d-862b-8cd65382b04c

* checkbox alignment is out
* No space between check and test
* Some disabled fields have a grey background, others have a slightly different background.  Fonts don't look faded enough for disabled text?

**Comment by thakuad** [comment]
grey out is fixed in this commit #2368
