### ISSUE TITLE
Re-index associated projects when a management unit (or program) is renamed

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2382]
To reproduce:
1) edit MU
2) Go to project explorer 
Note the old name is still displayed on the project explorer

**Comment by DaveDrynan** [comment]
Tested 26/9/24 - changed RASL program name to add in some extra text, saved.  Went into the project explorer and the amended name was visible instantly.  Changed the program name back to the original and got the same result.  PASS
