### ISSUE TITLE
User with editor role to the project cannot view the contents of the Admin tab

### ISSUE THREAD

**Issue by salomon-j** [AtlasOfLivingAustralia/fieldcapture#2391]
See sample project below.
https://fieldcapture.ala.org.au/project/index/21fcb5cf-19e3-4de1-b344-469abf62875
<img width="1166" alt="Screen Shot 2021-09-30 at 12 00 01 pm" src="https://user-images.githubusercontent.com/90952854/135379729-1f40d0b0-46b3-448f-bde1-5fe7974b6785.png">

**Comment by chrisala** [comment]
This is a duplicate.
