### ISSUE TITLE
1.1.1 Implement a user interface to add / remove these roles on the MERIT hub.

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2419]
* Add a section "MERIT access" to the Administration page in MERIT that allows a user with the FC_ADMIN role (merit Hub admin role) to add, remove and edit the user roles on the MERIT hub.
* Use the management unit MU Admin -> Permissions section as a guide when implementing this.
* Any user can be assigned the Hub admin or Hub grant manager role.
* Users who have a role on any existing MERIT project cannot be assigned the read only role.

**Comment by salomon-j** [comment]
https://upsource.ala.org.au/fieldcapture/review/FLDCP-CR-325
