### ISSUE TITLE
Create a new summary report for management unit core services reports

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2432]
Currently, the only report available is a full data download, which is cumbersome for use for tracking whether reports are due or not.
This task would be to create an equivalent of the Activity Summary download but for management unit reports.
The query interface should be updated for this report (and the existing report) such that the start date and end dates are selectable. 
Default start date should be 2018.
Default end date should be the current date.

- [x] Create new summary download
- [x] Update the user interface for management unit reports to allow date range selection

**Comment by salomon-j** [comment]
@chrisala 
Hi Chris, this is now ready again for code review.
