### ISSUE TITLE
Missing dashboards on some programs on management unit overview tab

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2439]
To reproduce:
* Open the Greater Sydney management unit in staging and production
* Compare each program tab on the overview tab.
Expected;
* They are the same.
Actual:
* Only 1 of the programs actually has a displayed dashboard, the others are missing it.

**Comment by chrisala** [comment]
This was due to the number of targets set by the combined set of projects in each management unit/program combination.  A large number of scores results in a large query URL which nginx was rejecting with a 414.
Temporary workaround was to increase the nginx header buffer size, but these large queries might be better as POST operations.

**Comment by chrisala** [comment]
https://github.com/AtlasOfLivingAustralia/ala-install/commit/ecffbc55e02d5700250b45023781f6b16d792423

**Comment by salomon-j** [comment]
Compared programs in staging and production, both environments showing exact data and 4 programs have dashboard.
