### ISSUE TITLE
Report association is not working 

### ISSUE THREAD

**Issue by salomon-j** [AtlasOfLivingAustralia/fieldcapture#2466]
Expected: 
When documents are attached within the project’s quarterly report it automatically associates the document to that quarterly report. 

Actual: 
Documents are attached but association to the report is not working. Currently, report association is manually done  through the Admin Documents tab.

**Comment by salomon-j** [comment]
Fix committed in Ecodata: https://github.com/AtlasOfLivingAustralia/ecodata/commit/4a3011a254f4dc5e13b057dd480c9fd4d7afadfb

**Comment by chrisala** [comment]
https://support.ehelp.edu.au/a/tickets/126450 - approved for release
