### ISSUE TITLE
Project explorer date facet is broken.

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2477]

**Comment by chrisala** [comment]
The two problems are:
1) The search string is cleared when a date is selected.
2) Selecting a date results in a loop of : page loads -> page reload triggered

**Comment by salomon-j** [comment]
Testing successful in MERIT test.
1. Query string with date filters - passed
2. Looping issue - passed

**Comment by salomon-j** [comment]
UAT completed as per comment in the ticket below:
https://support.ehelp.edu.au/a/tickets/126031
