### ISSUE TITLE
Create a report status that allows the report to remain incomplete

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2502]
The use case for this is some outcomes reports were delivered as paper copies for RLP projects that finished early, before the short term outcomes report template was developed.

The status should be treated as "Approved" for the purposes of report regeneration and project completion.

Rules:
* Only a FC_ADMIN can mark a report as CANCELLED (or maybe NOT_REQUIRED)
* The FC_ADMIN must enter a reason when cancelling a report, similarly to when withdrawing approval for a report.
* The reason will be displayed on the reporting tab to let other uses know why the report was cancelled.

**Comment by salomon-j** [comment]
Back end changes: https://github.com/AtlasOfLivingAustralia/ecodata/commit/8139c540bba97c8b39e59db1a89c1b6807247be0
