### ISSUE TITLE
Updates to the Report Type column of the Activity Summary download.

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2586]
- [x] Program configuration needs to be updated to include labels for existing programs
- [x] generated reports need to be updated to include those labels in the "generatedBy" field

**Comment by salomon-j** [comment]
@chrisala for your review is the script to update the generatedBy Report field.

**Comment by salomon-j** [comment]
https://support.ehelp.edu.au/a/tickets/155273
