### ISSUE TITLE
The "Remove User from MERIT" function isn't removing site (hub) roles

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2588]
To reproduce:
1) Assign a user some project/mu/organisation roles + use the "User Permissions for MERIT" to assign a site/hub level role
2) Use the Remove User from MERIT function to remove the user's permission.

Expected:
All project/org/mu roles are remove and the site (hub) level role is also removed.

Actual:
The site/hub level role remains, all other roles are removed.

**Comment by salomon-j** [comment]
Note* functional test will fail until the Ecodata changes is merge into dev

**Comment by salomon-j** [comment]
Created pull request in Ecodata - https://github.com/AtlasOfLivingAustralia/ecodata/pull/768
