### ISSUE TITLE
Investigate and fix error handling for document upload in reports

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2598]
The issue to be addressed here is that in a report that accepts attached images (e.g. RLP Output Report), if any of the attached images have a "broken link" i.e. the file associated with the image document cannot be found, the output in which the broken link exists cannot be saved.

There were several affected reports in the December reporting period affected by an error which broke the link by incorrectly moving documents.

However, this quarter there was a new report affected by this issue.  The broken link was a .MOV file, so likely the attached file was fairly large in size.  
Reasons this may have happened could be the attachment exceeded the upload limit (64 MB) or a timeout during upload due to a slow or disconnected network.
In the event this happens, we need to check:
1) that a document is not created without an associated file
2) that an attached image without an associated file fails validation
3) that the form section/output can be saved, even with a broken link.

**Comment by salomon-j** [comment]
Code update that will allow the form section/output to be saved even with a broken - 
https://github.com/AtlasOfLivingAustralia/ecodata/commit/084e6d2e3a4d85f3b264d8975f0394ec0d2cba64

**Comment by salomon-j** [comment]
Created pull request in Ecodata - https://github.com/AtlasOfLivingAustralia/ecodata/pull/767
