### ISSUE TITLE
Another weekly scheduled staging download failed

### ISSUE THREAD

**Issue by salomon-j** [AtlasOfLivingAustralia/fieldcapture#2603]
Another weekly scheduled staging download failed over the weekend, had a quick eyeball and the download issue is different from the reported issue last week.

**Comment by salomon-j** [comment]
https://support.ehelp.edu.au/a/tickets/151816

**Comment by salomon-j** [comment]
Downloaded Tabs/Activity Types:

Tabs: [Indigenous Employment and Businesses, Outcomes, Evaluation and Learning - final report, Project Administration, Progress, Outcomes and Learning - stage report, Biodiversity Fund - Outcomes and Monitoring, Site assessment, Fauna Survey - general, Flora Survey - general, Pest Animal Survey, Plant Survival Survey, Site Monitoring Plan, Water Quality Survey, Weed Mapping & Monitoring, Vegetation Assessment - Commonwealth government methodology, Community Participation and Engagement, Debris Removal, Disease Management, Erosion Management, Fencing, Conservation Grazing Management, Ecological Fire Management, Fire Management, Heritage Conservation, Management Plan Development, Management Practice Change, Conservation Actions for Species and Communities, Pest Management, Plant Propagation, Public Access and Infrastructure, Research, Revegetation, Seed Collection, Site Preparation, Water Management, Weed Treatment, Works Planning and Risk, Upload of stage 1 and 2 reporting data, Indigenous Knowledge Transfer, Training and Skills Development]

**Comment by salomon-j** [comment]
I'm suspecting the issue happens during the batch run. Didn't replicate the issue in staging and in my local when the report was executed independently. Will wait until the next batch run this weekend.

**Comment by salomon-j** [comment]
This download failed again yesterday 07/08/2022. What change after a few weeks of not having download issues was Ecodata 3.9-SNAPSHOT was deployed in test and staging last Thursday(04/08/2022). Prior from the weeks which wasn't failing was ecodata 3.8.2-SNAPSHOT was running in test and staging.

**Comment by chrisala** [comment]
This is caused by a sheet name clash between Participant Information from Ecological Fire Management and Participant Information from Fire Management.  
(The Biodiversity Fund is the only program that has both, as one was removed in favour of the second).
It's not clear to me at the moment why the 3.8.2 version works, and the 3.9-SNAPSHOT fails.

**Comment by salomon-j** [comment]
It's also the same fix I've done in https://github.com/AtlasOfLivingAustralia/fieldcapture/issues/2597
I've updated now the section names for both forms.
It's really strange the error didn't happened in Ecodata 3.8.2-SANPSHOT hence I was thinking it might be a different issue.
