### ISSUE TITLE
Include ESP reporting data in the download

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2608]
No special rules apply, it should be treated the same as other downloadable activities.

**Comment by salomon-j** [comment]
Created PR in Ecodata - https://github.com/AtlasOfLivingAustralia/ecodata/pull/769

**Comment by salomon-j** [comment]
Added ESP in the scheduled download - https://github.com/AtlasOfLivingAustralia/ala-install/commit/e59def5f1a329014c5d70705ffe11932373e5cf4
