### ISSUE TITLE
Support collapsible explanatory text in the ESP forms

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2685]
To increase usability of the ESP n/a for form sections, the explanatory text needs to be collapsed by default to make the alternative "I didn't do this during this period" option visible at the same time so the n/a is not used when the other should be.

See: https://github.com/AtlasOfLivingAustralia/ecodata-client-plugin/issues/153

And; https://support.ehelp.edu.au/a/tickets/155513

**Comment by chrisala** [comment]
After discussion, the preferred implementation for this item is to include the ability to make a collapsible / collapsible by default description available in between the form and the "not applicable" checkbox.
This requires a different implementation than suggested in https://github.com/AtlasOfLivingAustralia/ecodata-client-plugin/issues/153 as the form section header and not applicable is rendered in MERIT rather than the ecodata-client-plugin

Options to implement this include:
* Include a "description" or "explanation" attribute in the FormSection domain object and ecodata user interface, as well as a collapsed by default attribute.  This explanation should accept (and be rendered with) markdown on activity forms.
* Include the "description" in the services.json (which will be modified for RLP 2 anyway) to override the form description if the form section is associated with a service.

**Comment by salomon-j** [comment]
https://support.ehelp.edu.au/a/tickets/157364
