### ISSUE TITLE
Create the ERF - Priority Species Grants Final Report

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2715]
The report is a mix of the Right Way Desert Fire Final Report but with the services from the Bushfires - States progress/final reports.

**Comment by salomon-j** [comment]
https://support.ehelp.edu.au/a/tickets/162303

**Comment by salomon-j** [comment]
Implementation of #2703 have to be finished before proceeding with the pending requests to display full widget of services.

**Comment by salomon-j** [comment]
new change requests -> https://support.ehelp.edu.au/a/tickets/168543

**Comment by salomon-j** [comment]
Approved for production -> https://support.ehelp.edu.au/a/tickets/168543
