### ISSUE TITLE
Project settings tab issues with ESP projects

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2741]
ESP projects have the UI that sets the associatedProgram/associatedSubProgram rather than the programId, but because they've been configured with programIds changing this setting does nothing.

**Comment by salomon-j** [comment]
Legacy Programs:
1. 20 Million Trees Service Providers
2. Biodiversity Fund
3. Caring for Our Country 2
4. Cumberland Plain
5. Green Army
6. National Landcare Programme
7. Reef 2050 Plan
8. Reef Trust
