### ISSUE TITLE
A bug exists that can somehow duplicate report sites 

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2745]
On two separate occasions over the last year, somehow during an RLP report update all of the site features get duplicated.

**Comment by chrisala** [comment]
There is a possibility that this is related to the cancel bug that was fixed in 3.1

**Comment by chrisala** [comment]
To reproduce:
1. Find a report and add spatial data to it. Save and reload the page.
2. Logout in a different tab.
3. Modify a value in the report and press save.

4. You'll get an error about a session timeout. Click the link in the dialog and re login.
5. On reload you'll be presented with a message about unsaved data. Dismiss it.
6. Press save.
7. Reload the page without further edits. At this point there is a good chance the spatial data in the report has been duplicated.

Also, note you will not be able to perform all of these steps exactly if you are running this branch as the re-login mechanism has changed (step 4 opens in a new tab and step 5 won't happen), but this should reproduce it in test/staging.

**Comment by DaveDrynan** [comment]
Tested 23/8/24 using procedure above - unable to replicate as changes to the logout banner mean that when the second tab is logged out, the original tab also logs out.  Tried with an amended version of the above procedure with the same result.  Previous attempts indicate that sites were not duplicated following both procedures prior to the change in logout behaviour - PASS
