### ISSUE TITLE
ESP Reporting Period Dropdown

### ISSUE THREAD

**Issue by Blaz-Sculac** [AtlasOfLivingAustralia/fieldcapture#2775]
Allow a Not required report to be selected in the Reporting Period dropdown menu. When opening template a message (This report has been marked as Not required. Please contact your ESP Project Manager for further information.) to appear. 
Otherwise, We may not need to select these reports. Could we apply the greying out (in the reporting period dropdown - USER view ) so that they can’t select that reporting period and it has "NR" at the end of the reporting period date?

**Comment by chrisala** [comment]
This was implemented in 2.9
