### ISSUE TITLE
Allow form auto-population (e.g. ESP submission report calculations) to run even when the report is "finished"

### ISSUE THREAD

**Issue by Blaz-Sculac** [AtlasOfLivingAustralia/fieldcapture#2776]
Remove current rule: Do not allow submission re-calculations once site report is marked as “finished”.  
Instead, only apply **do not allow submission page recalculation** when the report is either in submitted phase or approved phase.

Ultimately, if corrections/updates are required, GMs should be able to return reports for Stewards to update as needed which should then recalculate the submission page (without any further interferrence).

**Comment by chrisala** [comment]
I have re-titled this issue to better reflect the scope of the change.  This will affect all pre-populations done by forms.  Notable examples are:
* The outcomes reports and some final reports have a lot of data pre-populated from the MERI plan (outcomes, KPIs etc)
* The RLP annual report calculates annual delivery against targets from outputs reports
* The ESP submission form calculates total cost of implementation actions for that stage.
