### ISSUE TITLE
Replace existing spatial data upload system. New system should not allow “large” spatial files to be uploaded – but gives the opportunity to correct them

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2789]
The purpose of this issue is to allow users to upload shapefiles (and possibly other formats such as geojson/KML) into MERIT via javascript tooling.  
(e.g. shapejs and leaflet).

This will:
* Remove the dependency on the spatial portal 
* Provide visual feedback to the user about the sites they will be creating before it gets loaded into MERIT
* Allow MERIT to detect overly complex (and hence large) data sets and optionally simplify (via turfjs simplify) the site before it gets loaded and causes subsequent performance issues.
* Potentially allow this function to be used in a reporting context 

For usability/consistency with the current system, we ideally keep a similar workflow (to the UI portion) as the current system.  e.g.
1. User presses button (or drag & drop) to attach file
2. We create a table with an row for each row/geometry in the shapefile. 
3. We allow a selection of the shapefile attribute to populate the site name/externalId
4. We allow some rows to be excluded from the upload (less important as I suspect almost all users upload all shapes in their files)

**Comment by temi** [comment]
Blaz tested and passed. 7/11/24
https://support.ehelp.edu.au/helpdesk/tickets/217044
