### ISSUE TITLE
Dashboard targets should be displayed with a maximum of 2 decimal places

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2830]
To reproduce:
A project used a target of 94.33km for length of weed treatment.
The dashboard is displaying the floating point representation to full precision.

The dashboard currently limits the delivered amount to two decimal places, but not the target.  The target should also be formatted to a maximum of 2 decimal places.

**Comment by salomon-j** [comment]
https://support.ehelp.edu.au/a/tickets/172890
