### ISSUE TITLE
Rework of MERIT organisation relationships and the organisation page/s

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2880]
https://support.ehelp.edu.au/a/tickets/177402

**Comment by kaleemullah786** [comment]
Hey, I would like to work on this. Can you provide more details

**Comment by chrisala** [comment]
Thanks @kaleemullah786 but we aren't looking for contributions at the moment

**Comment by kaleemullah786** [comment]
Alright
