### ISSUE TITLE
Update the Community/Stakeholder Engagement project service form

### ISSUE THREAD

**Issue by salomon-j** [AtlasOfLivingAustralia/fieldcapture#2909]

**Comment by salomon-j** [comment]
[Community_Stakeholder Engagement.xlsx](https://github.com/AtlasOfLivingAustralia/fieldcapture/files/11763891/Community_Stakeholder.Engagement.xlsx)

**Comment by chrisala** [comment]
We've been asked to change the target measure for this service to simply a sum of the number of events.
This will affect the design of the form where the "actual" and "invoiced" are displayed (there will now be only one actual and one invoiced measure)
