### ISSUE TITLE
Update Establishing and Maintaining Pest Animal-Free Enclosures project service form

### ISSUE THREAD

**Issue by salomon-j** [AtlasOfLivingAustralia/fieldcapture#2912]
[Establishing and Maintaining Pest Animal-Free Enclosures.xlsx](https://github.com/AtlasOfLivingAustralia/fieldcapture/files/11763950/Establishing.and.Maintaining.Pest.Animal-Free.Enclosures.xlsx)

**Comment by chrisala** [comment]
Released with 3.1
