### ISSUE TITLE
Create sub program "NRM Procurements 2024"

### ISSUE THREAD

**Issue by salomon-j** [AtlasOfLivingAustralia/fieldcapture#3006]
Program - Saving Koalas Fund
Sub program - NRM Procurements 2024
(copy of the Natural Heritage Trust – Recovery Actions for Species and Landscapes)

https://support.ehelp.edu.au/a/tickets/187279

**Comment by salomon-j** [comment]
Status - created in MERIT test

**Comment by chrisala** [comment]
Projects were extended instead so this is no longer necessary.
