### ISSUE TITLE
Implement a report to display projects marked as "Promote on homepage"

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#304]

**Comment by chrisala** [comment]
What are the criteria to use for this?
Does a project both have to be flagged by the user & the grant manager?  Or just one?
On that subject, should a grant manager only be able to recommend a project that the user has also flagged?

**Comment by chrisala** [comment]
I have added two facets to the project explorer, one to filter user nominated projects, one to filter grant manager projects.  (It was much easier to add two separate ones than group the two into a single facet).
Is is OK?

**Comment by Mitchdoe** [comment]
I tried to recommend a few projects as a GM via the GM tab, to test that facet selection. It doesn’t seem to save my selections though when I reload the page. Otherwise the facet selection is fine, once we have some GM nominated projects, we can apply both together to get a narrower list.
