### ISSUE TITLE
Refactor "Project Explorer" page

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#306]
- Needs to be able to be loaded dynamically on homepage
- Needs to be able to be displayed via a menu selection.
- Tabbed style layout needs to be changed to an accordion style layout.
- Facet selection should start collapsed.
- Selection of a separate accordion should not impact the current facet selection.

**Comment by chrisala** [comment]
Do you want to have a look at this in fieldcapture-dev.ala.org.au please Andy?

**Comment by AndyWestcott** [comment]
Looks good. Initital concept had the map greyed out in the background, is that a Giraffe wall papering excercise?

**Comment by chrisala** [comment]
Yes, it still needs some styling.

**Comment by chrisala** [comment]
The about section under the project explorer needs to be removed.
