### ISSUE TITLE
Display project sites as a heat map above a certain number.

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#307]

**Comment by chrisala** [comment]
Looking for feedback on this.
I've set the map to use a heatmap when the number of projects is > 250.

**Comment by AndyWestcott** [comment]
Hi chirs, reviwing now. Will get comments back asap. See earlier issue that flagged if our need to comment on home page was dependant on giraffe doing some more work.

**Comment by chrisala** [comment]
Review comments indicate that the map is required to be able to detect the number of sites inside the current extent and decide on that basis whether to display a heat map or dots.

**Comment by AndyWestcott** [comment]
As discussed at meeting of 11/11/15, full project MERIT project list can remain heat map for short term. Once any filter engaged move to dots instead of heat map.
