### ISSUE TITLE
Increase outcome selection restriction

### ISSUE THREAD

**Issue by salomon-j** [AtlasOfLivingAustralia/fieldcapture#3084]
When there are 5 or more Primary Outcomes configured in a sub program the primary investment priority for the last outcome will be a multiple selection even when the "supportsMultiplePrioritiesAsPrimary" is set to false.

https://support.ehelp.edu.au/a/tickets/193355

**Comment by DaveDrynan** [comment]
tested 23/8/24 - added extra outcomes to an NHT program (RASL), and the multi-select was still available for the final outcome as expected.  Chris updated the config to remove the multi-select and this worked as expected. - PASS
