### ISSUE TITLE
Implement a blog feature   

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#309]
- Replaces project stories and news and events.
- Date, title, text (example includes links, what formatting do we support), image, tags.
- Tags include "news", "stories", "photos"?
- "infinite scrolling" when displaying the blog.

**Comment by chrisala** [comment]
I have prototyped (meaning it's not complete) something for this blog feature in order to generate some discussion on how we want this to work.  
Please have a look and give me some feedback.
For the homepage news and events, you can add entries using the admin menu "Edit Site Blog" option.
The project site blog doesn't have any links you can use to edit, but the gist is blog entries with type "News and events" get rendered in the news and events section and "Project stories" go into the project stories section.

**Comment by Mitchdoe** [comment]
Hey Chris,

Project blog looks good.
Can’t seem to load more than 3 homepage blogs and I can’t edit or delete them. Adding a photo didn’t work for me either. Does the photo need to be hosted somewhere online for it to show? I.e. I can’t just attach a photo from my desktop?

Cheers
Mitch

**Comment by chrisala** [comment]
Thanks Mitch,
Edit & delete are "not implemented" at the moment.  The reason the image doesn't work is I've configured the dev server to load the images from prod (so the home page images look pretty) but that means images loaded to dev don't display.  (It's one or the other unfortunately)
The main things I have questions about are:
* Are you OK with the structure of the blog (i.e. the data we collect and how it's displayed - any fields missing for example)
* Are you OK with project stories having the same format / layout as news & events?
* Is this how you expected the feature to work?

**Comment by AndyWestcott** [comment]
Hi Chis,

if read more is selected from the 'latest news' section it would be ideal for it to send you to the project page. Imagine that woudl require putting a hyperlink in somehow?

With wording, can we make it 'latest news' on both home page and "Administration". currently says "Site blog" on administration page.

**Comment by AndyWestcott** [comment]
•Are you OK with the structure of the blog (i.e. the data we collect and how it's displayed - any fields missing for example): When you say blog here, is this project page or home page? When creating a new 'Latest News' entry, via the Administration/Site Blog it is exactly how I expecetd it to work. On the the "type" lets have 3 options. project stories (so outcomes from a project type stuff), News and events (highlighting a field day etc) and Merit alert (a feature we use to let people know about bugs, enhancements etc)


 •Are you OK with project stories having the same format / layout as news & events? yep
 •Is this how you expected the feature to work? Sure is

**Comment by chrisala** [comment]
I've implemented the blog feature for projects, added the ability to select a stock icon instead of uploading a photo, added an option to include a URL the "view more" icon will link to and fixed some bugs.
Please test and give feedback.

**Comment by Mitchdoe** [comment]
Looks good, I was able to add new entries with no problem, icons work well. Might need to make the link a bit more obvious by using some words to direct people to the URL.
Are we still planning on restricting each entry to a fixed size in the blog? And also have the blog set at a fixed size with a scrollable option inside? Will there be a limit to the amount of active blog entries?

**Comment by chrisala** [comment]
Any suggestions about the wording?
I am not sure about restricting the size - It's probably not necessary in the project page and the home page is edited by the team so I'd probably err towards  not restricting and see how it goes.
I'll add the scrolling this morning.
