### ISSUE TITLE
Add "Outcome" section to finished projects.

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#310]
- The content should be taken from the project final report activity.  (Double check which field)

**Comment by chrisala** [comment]
Hi Andy, in the outcome section of the project page can you please clarify:
1. Only show for completed projects
2. Do you want environmental, economic & social outcomes or a subset?

**Comment by AndyWestcott** [comment]
1: yes
2: Ideally we would be not sure we will get approval to make that public. Need to work on the policy around that. For not just the 'project dashboard' for completed projects.

**Comment by chrisala** [comment]
2. Do you mean the targets section?  That is currently being displayed for all projects.  This has already been implemented in dev - take a look at some of the completed projects.

**Comment by AndyWestcott** [comment]
1: yes, whats in dev is good.Can we limit it by program? Also remove from the next promotion to prod? Need to work on the messaging to recipeint on this.

**Comment by chrisala** [comment]
Removed dec milestone for this and reverted code.

**Comment by chrisala** [comment]
Replaced by user configurable content so as to not bias reporting for public view.
