### ISSUE TITLE
Make the help links section editable.

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#313]
- More resources to help page which renders these links.
- Each item needs to be editable.

**Comment by chrisala** [comment]
The current design calls for exactly 5 help links.

**Comment by chrisala** [comment]
Andy, please check this one for me.  You can edit the links using http://fieldcapture-dev.ala.org.au/admin/editHelpLinks

**Comment by AndyWestcott** [comment]
Hi chirs, I get a "Access denied: User does not have alaAdmin permission" when i try to click on 'help resources'. Assume that button allows us to edit the links to the resources? If yes, then thats perfect.

**Comment by chrisala** [comment]
I've fixed that error in the latest build

**Comment by chrisala** [comment]
Can you please retest for me Andy?
