### ISSUE TITLE
Develop data pre-pop routine for the SAF annual report

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#3142]
https://support.ehelp.edu.au/a/tickets/198540

**Comment by salomon-j** [comment]
new change requests: https://support.ehelp.edu.au/a/tickets/203287
changes in test

**Comment by salomon-j** [comment]
SAF Annual report moved in production today - https://support.ehelp.edu.au/a/tickets/203548
