### ISSUE TITLE
Create the RCS Annual Report

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#3146]
https://support.ehelp.edu.au/a/tickets/198746

**Comment by salomon-j** [comment]
Feedback/change requests: https://support.ehelp.edu.au/a/tickets/199831

**Comment by salomon-j** [comment]
new change requests: https://support.ehelp.edu.au/a/tickets/203798

**Comment by salomon-j** [comment]
latest template: https://support.ehelp.edu.au/a/tickets/203798
