### ISSUE TITLE
Make the MERI plan tab public

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#321]
- The MERI plan tab should be publicly viewable for NLP projects.
- Budget & Announcements information should not be shown.
- Suggest moving the budget and announcements onto separate tabs (not the editing, just the display) so visibility can be more easily managed.

**Comment by chrisala** [comment]
Comments Andy?

**Comment by AndyWestcott** [comment]
Could we have a function, doesnt have to be in the short term, that allows users to see the whole lot (MERI plan, budget and announcements) in one place? Just thinking about ease of assessment. Tyrim to avoid having to review updates across to many tabs

**Comment by chrisala** [comment]
Do GMs normally do the review on the "view" tab or the "Edit" tab?  Because the workflow buttons are all on the "edit" tab, (e.g. approve plan etc)

**Comment by AndyWestcott** [comment]
Good question, will ask them.

**Comment by AndyWestcott** [comment]
Bit of both it turns out. not a big issue, can instruct them to review on the Admin tab. A button that PDFs all the MERI plan would be handy long term.

**Comment by chrisala** [comment]
So can we move the budget and announcements onto a separate tab (for viewing purposes) so we can make the whole MERI plan tab public?

**Comment by AndyWestcott** [comment]
Sure.

**Comment by AndyWestcott** [comment]
Hi chirs, not sure if I have flagged that  MERI plans going public is only for NLP, regional funding projects

**Comment by chrisala** [comment]
I was aware of the NLP part, but not that it was going to be restricted to Regional Funding projects.

**Comment by chrisala** [comment]
Hi Andy, this is in test now.

**Comment by AndyWestcott** [comment]
Hi Chris

This is better than expected. Testing of NLP - regional funding shows that checking when logged out hides the budget and announcments, logging in presents them back in their usual place. That is a great solution.

have also tested:
NLP - Local Programmes-Working as expected
NLP - Small grants - Working as expected
NLP - 20MT - Working as expected
NLP - Landcare network grants - Working as expected
CFOC - Regional delivetr - Working as expected
CFOC - CEG - Working as expected
CFOC - Reef rescue - Working as expected
CFOC TAG - Working as expected
CFOC TAG EOI - Working as expected
BioFund - RD1 - Working as expected
BioFund - RD2 - Working as expected
BioFund - reef rescue - Working as expected
BioFund -Rd 2 EOI - Working as expected
BioFund Rd 2 - Northern - Working as expected
Biofund - tas - Working as expected
20MT service providers - Working as expected
Reef trust - Working as expected
Cumberland plain - Working as expected
Environmental Stewardship - Working as expected

**Comment by chrisala** [comment]
Andy, should a project editor be able to see the budget & announcements or just the admin?

**Comment by AndyWestcott** [comment]
whats current functionality? Can they see the MERI plan tab currently?

**Comment by chrisala** [comment]
Currently they can see the read only version of the tab, but not the editable version.

**Comment by chrisala** [comment]
New requirement: only approved plans should be visible.
