### ISSUE TITLE
Synthesisting and finalising baseline data is showing the data set id in view mode

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#3267]

**Comment by chrisala** [comment]
To test:
1) Fill out the Synthesising and finalising baseline data service in a report.
2) Look at the read only / view version of the report.
3) Ensure the data set name/label is displayed in the view report, not the data set id. 
This can be compared to the production system for contrast.

Note also that this same issue affected the read only view display of the investment priorities in the outputs report.

**Comment by cbackhouse** [comment]
Tested 24/25 Q4 report (https://fieldcapture-test.ala.org.au/project/viewReport/dabc7e5d-81ce-40bf-8f74-8ecf3c7ce055?&reportId=993daece-7815-4943-b08a-80337d314838) on 22/8/24. Confirmed the view mode report displayed the correct data set name.
