### ISSUE TITLE
Fix reference to old support email

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#3268]
See https://support.ehelp.edu.au/a/tickets/206481

**Comment by DaveDrynan** [comment]
Tested 15/8/24.  Made [MERIT-Admin@dcceew.gov.au] an FC_USER  in the system settings, then tried to add as a Grant Manager to MERI-17.  Error/warning appeared with new @dcceew address. Passed UAT.
