### ISSUE TITLE
Users with the organisation admin role cannot see the Admin->Documents tab

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#3282]
The admin role needs to be able to view and attach documents.
The read only role needs to be able to view those documents and the organisation permissions.

**Comment by DaveDrynan** [comment]
Tested 15/8/24 on Organisation DEPARTMENT OF ENERGY ENVIRONMENT AND CLIMATE ACTION. 
Confirmed all system roles in test were correct (Admin & Editor = FC_USER. Read Only = FC_READ_ONLY).  Added Admin & Editor to Org Permissions.
Logged in as [MERIT-Admin@dcceew.gov.au]: able to view/edit/upload documents via the Admin Tab - PASS
Logged in as [MERIT-ReadOnly@dcceew.gov.au] - able to view/download documents, but not able to upload or edit - PASS
Logged in as [MERIT-Editor@dcceew.gov.au] - Admin tab not visible, so no access to documents at all - PASS
Overall PASS for UAT.
