### ISSUE TITLE
Projects without a MERI plan cannot be submitted

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#3286]
It appears the changes for MERI plan locking have removed the admin user actions from the page for projects that don't have a MERI plan.  A possible workaround is to use the configurable meri plan with no template items for these projects?

To reproduce:
1) Find an ESP project in test/staging.  
2) If the MERI plan is approved, unlock the plan as a grant manager.

Expected:
There exists a mechanism to submit the plan.

Actual:
There are no controls displayed to admin or grant manager users so the plan cannot be submitted.

**Comment by DaveDrynan** [comment]
Tested 15/8/24 on https://fieldcapture-test.ala.org.au/project/index/80241fb7-b2b6-4ec3-ba61-9357bd2a0be1?template=index
Added myself as Grant Manager, pressed 'Modify MERI plan', plan was unapproved. Had the button option to submit the plan for approval, pressed, had to enter TechOne/SAP code (value = N/A), able to re-approve plan.  PASS UAT.

**Comment by DaveDrynan** [comment]
Note this didn't work in staging, just in test.  But passed in test.
