### ISSUE TITLE
Add facets for start and end date to the Project Explorer

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#3291]
The rules should be:
For each of project planned start and planned end date, have a UI section (similar to the project dates one) where the user can select a start and end date of a range.
This range would apply to the date in question.

E.g. for the project start date, the range should select projects with:  "from date" <= project start date < "to date".
If "to date" is not supplied, use "from date" <= project start date
If "from date" is not supplied use project start date < "to date"

The same rule should apply to the project end date.

The main use case for these facets is to find projects that start on or after a specified date.

**Comment by Blaz-Sculac** [comment]
Does it matter which platform this is checked in (ie. Staging or Test)

**Comment by chrisala** [comment]
> Does it matter which platform this is checked in (ie. Staging or Test)

Sorry Blaz we are having some issues with our build system which haven't been sorted out that is preventing us deploying anything.  I should move this back to QA

**Comment by Blaz-Sculac** [comment]
[SEC=UNOFFICIAL]
Hi Chris

Thanks for letting me know. Should I test anything today? I will only be in till 12:30.

Blaz

**Comment by temi** [comment]
Dave tested an passed UAT for it on 12/9/2024
