### ISSUE TITLE
Include Marine Parks as a selectable known shape for MERIT sites

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#3302]
See https://support.ehelp.edu.au/a/tickets/208028

  [id:'cl11194', name:'Australian Marine Parks (2024)']

**Comment by DaveDrynan** [comment]
tested 16/8/24.  Created a new site using a 'known shape'.  Able to select 'Australian Marine Parks  (2024)' layer, then selected Ashmore Reef - displayed OK and saved OK - PASS.
