### ISSUE TITLE
Remove user from MERIT function is broken for some users

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#3316]
After the call to userdetails to retrieve the userId for the supplied user email, there is a sanity check that userName == supplied email

What might be happening here is that the account was created with an older email and has subsequently been updated causing this sanity check to fail.

**Comment by DaveDrynan** [comment]
Tested 26/9/24.  Used the MERIT-Editor@dcceew.gov.au test account.  Changed the email address by removing the n-dash in the ALA authentication system. Logged back in as FC_ADMIN, and was able to use the new email address to remove the user from MERIT and didn't get any errors saying the user didn't exist.  PASS
