### ISSUE TITLE
Decommission green army monthly / quarterly reports

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#353]

**Comment by chrisala** [comment]
I've removed the reports in dev - this has had the result of removing the reporting tab (as the tab is only shown if there are reports to complete).
Please have a look and see if it is behaving as intended.

**Comment by Mitchdoe** [comment]
Hey Chris,

I’m checking with the GA team but it looks good to me, can we also please remove the dashboard option to run Green Army reports?

[cid:image001.png@01D11AE9.FBDAD5E0]

Cheers
Mitch

**Comment by chrisala** [comment]
Hi Mitch - reports have been removed.
I've also deployed this to test as this is now going out on the 23rd of November with the MERI plan change.

**Comment by Mitchdoe** [comment]
Thanks Chris, will let GA team know
