### ISSUE TITLE
Reporting deadlines are programme based

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#356]
Green Army: 20 business days.
Other programmes: 40 business days.

**Comment by chrisala** [comment]
This has been implemented.  I have generated the reports for dev so they can now be compared for corrected against production.
To see the reports for a project you need to add yourself as a grant manager or admin so they appear on your profile page.

**Comment by chrisala** [comment]
Green army reports have been assigned 20 days.
Other programmes have been assigned 43 days.
There is no mechanism to update due dates after the reports have been generated so we need to finalise these numbers before we deploy into production.

**Comment by AndyWestcott** [comment]
Went over tge grant manager tab with Masters yesterday. have the following answers to question:
1-What should the defalt sort be? Programme
2-Shoudl GM tab be the landing page? Masters thought it best to retain the current setup, that way the new work on the home page is promoted to them.

**Comment by chrisala** [comment]
It was decided that including deadlines in MERIT would be too controversial so this is no longer wanted.
