### ISSUE TITLE
Sorting arrows for grant manager tab

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#359]

**Comment by Mitchdoe** [comment]
Similar issue to this one Chris - on the initial designs from Giraffe there were + and - symbols on the RHS of the project explorer facets to expand and collapse them. Is this manageable? Most people aren't finding it intuitive to click on the title (map, projects, dashboard, download) to expand/collapse.

**Comment by chrisala** [comment]
This is in dev now, including the requested changes to the project explorer.

**Comment by Mitchdoe** [comment]
Perfect, thanks Chris
