### ISSUE TITLE
Selective association of activities with programs/sub-programs

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/fieldcapture#40]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=517
*date:* Mon Jan 13 15:20:13 2014
*author:* CoolDa...@gmail.com
 ---

New requirements for activities under the Green Army programme suggest that we need to be able to selectively associate activities with programs and perhaps even sub-programs so that only activities relevant to a particular program are selectable in that program context.

This would also facilitate some requirements for BDRS migration.

**Comment by chrisala** [comment]
Implemented.
