### ISSUE TITLE
Changes to the MERIT navigation toolbar

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#406]
1.       Can we remove the “My projects” tab?
2.       Can we rename the [username] tab to “My projects”? It was found to be confusing to have 2 tabs which essentially do the same thing, the thinking is to scrap the dropdown option and only have “My projects” and “My organisations” tabs.
3.       Scrap the hover text over the [username] button that says “profile page”.
4.       When you click on the [username]/”My Projects” tab, can we change the heading from “Your Projects” to “My projects” for consistency?
5.       Following on from this, could we change the URL section “user” to “myprojects” and the tab heading “User Dashboard” to “My projects”? See screenshot.
6.       Can we place white or grey text above the “Logout” button that is similar to that on the ALA website? I.e. “G’day, <user name>” or “G’day, <email>”?

**Comment by Mitchdoe** [comment]
Hey Chris,

Can we also add a link to the org list/ org hub under the "My Organisations" tab? When you log in without having an organisation you see the message [You aren't a member of any organisations].
Can we add in underneath a link underneath that which says something like "Find your organisation here"?

**Comment by chrisala** [comment]
I'd prefer not to add that link until we fix the performance/search of that organisation list page. 
 We'd also need some way of explaining what to do once you've found your organisation - a member of an organisation is automatically assigned membership of that organisations projects.

**Comment by Mitchdoe** [comment]
Yeah agree it should be tied in together. Our thinking was to put some basic instructions somewhere near the top of the org list (and maybe on org pages as well) that says something along the lines of "email the merit inbox to nominate yourself as an organisation administrator". Have to put some text in about what this role can do and we have to work through how they get permission from their org to have this role. I.e. is it sufficient for them to be an admin on one project for their org, for us to then assign them as an admin to all projects for that org.

**Comment by chrisala** [comment]
I have implemented most of these changes, the exception is the URL is /project/mine instead of myprojects.  
I have moved the organisation change to another issue.
