### ISSUE TITLE
Changes to annoucements

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#425]
Update help text:
column ‘When will successful applicants be announced’
 
Current hover help text:
 
If this is a funding announcement, please provide a two week window of when you anticipate the announcement of the successful funding recipients will occur, for example ‘12/07/2015 – 26/07/2015”
 
Proposed changes:
 
If this is a funding announcement, please provide a single date of when you anticipate the announcement of the successful funding recipients. If you are unsure, provide a two week window, for example ‘12/07/2015 – 26/07/2015’and update to a single date when confirmed.

**Comment by Mitchdoe** [comment]
Can we also add sorting features to this table, particularly around dates? i.e oldest to newest. Understand it is difficult with the text box also containing free text ability, is this possible?

**Comment by chrisala** [comment]
I've added sorting on the organisation bulk edit announcements table.
Does it need to be on the other tables?

**Comment by Mitchdoe** [comment]
Which other tables?

**Comment by chrisala** [comment]
There are announcements on: 
1. Organisation admin -> Bulk edit announcements
2. Project home page -> MERI Plan tab (read only, had a table with announcements)
3. Project home page -> Admin Tab -> MERI Plan section
4. Project home page -> Admin Tab -> Project Announcements section

I've added sorting on (1), which would be the largest table.  Does it need to be on 2, 3 or 4?
