### ISSUE TITLE
Stage report preview

### ISSUE THREAD

**Issue by Mitchdoe** [AtlasOfLivingAustralia/fieldcapture#477]
Previews generated for stage reports appear to jumble the sections of the Progress, Outcomes and Learning form in a random order.
e.g. in the form the order is:
1. Overview of Project Progress
2. Environmental, Economic and Social Outcomes
3. Implementation Update
4. Lessons Learned and Improvements.

These sections appear to randomly change order, as do the sub-sections within each section. They should mirror the order in the form.

**Comment by chrisala** [comment]
The sections should now appear in the order specified.
