### ISSUE TITLE
Inappropriately returned to homepage.

### ISSUE THREAD

**Issue by Mitchdoe** [AtlasOfLivingAustralia/fieldcapture#482]
Noticed that a couple of different things return you to the homepage:
Clear filters in the project explorer - this should leave you on the project explorer page
Logging out - this should return you to the page you were on (i.e. a project so you can check which docs are public, etc.)

**Comment by chrisala** [comment]
Can you think of any other pages where it would be useful to return to the current page?  Most pages in the system are not public and returning to them would result in a redirect to the home page with an authorization error.  For normal users, logging out would normally represent the end of a session with MERIT.

**Comment by Mitchdoe** [comment]
If you log out from within a project, can we make the default that you are returned to the project overview page? With public documents and public MERI's a lot of users are wanting to check what the public can and can't see from their project so this would be useful.
Likewise for an organisation page.
Project explorer should leave you on the project explorer.
Can't think of any other pages that really would need this.
