### ISSUE TITLE
Upload shapefile button colour

### ISSUE THREAD

**Issue by Mitchdoe** [AtlasOfLivingAustralia/fieldcapture#483]
Button is grey until you hover over it, at which point it turns green. It should always be green.

**Comment by chrisala** [comment]
I can't reproduce this - for me the button remains disabled (grey) until a file is attached.  Once a file it attached it turns green (hover makes it slightly darker green).
I've tested with Chrome & Firefox 43.

**Comment by Mitchdoe** [comment]
Working for me now in Firefox (24.5), I had a couple of Grant Managers flag it with me, I suspect they either attached an incorrect file or were using far older browser versions.
