### ISSUE TITLE
Email notifications on MERI plan submission, acceptance and rejection required

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/fieldcapture#49]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=558
*date:* Tue Feb  4 22:38:02 2014
*author:* CoolDa...@gmail.com
 ---

DoE request `#17`
MERIT to send a project submission email to grant manager once grant recipient submits report.

**Comment by chrisala** [comment]
Done.
