### ISSUE TITLE
Case study tab on home page

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/fieldcapture#51]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=563
*date:* Wed Feb  5 16:02:10 2014
*author:* CoolDa...@gmail.com
 ---

DoE requirement `#47`
Case studies to be displayed as additional tab on home page. Projects to nominate if they would like to be a case study when submitting reports. (links with [ issue 538 ](https://code.google.com/p/ala/issues/detail?id=538) (DoE`#27`))

Comment - PB 6/2/14
This would probably be a rolled-up listing of truncated project narratives (see [ issue 538 ](https://code.google.com/p/ala/issues/detail?id=538)) with a "show more" link to the project overview page containing the full story, and maybe also icons to flag whether images and video media are attached to a particular project.
The listing should be responsive to the keyword search and filter selections like other tabs on the home page.

Note that [ issue 538 ](https://code.google.com/p/ala/issues/detail?id=538) will likely need further enhancement to fully satisfy the requirement.

**Comment by chrisala** [comment]
Replaced by site redesign work.
