### ISSUE TITLE
Second approval step to org access

### ISSUE THREAD

**Issue by Mitchdoe** [AtlasOfLivingAustralia/fieldcapture#511]
We had a region add a Grant manager as an editor to their organisation. The GM was across all of their regional projects, but nothing else, so they had to go change access in each project (couldn't bulk change or delete). Might need to come up with another way to manage org/project access. Possibilities include the individual having to approve their appointment to an org, i.e. the GM would have had to accept the editor role for the org before having their permissions changed.
Could also look into managing project access via the My Projects page. Could mean adding another column to the table which shows access and contains ability to change it. Anyone have better ideas?

**Comment by AndyWestcott** [comment]
Why did the region add them? Could they have gone into the organistion tab/manage access/then changed it to GM there? Can externals even add grant managers?

**Comment by chrisala** [comment]
Externals can't add grant managers, but the problem here appears to have been they added the GM as an org editor, which then downgraded their project access to editor.
It should be easily fixed though - as Andy mentioned, the GM should have been able to go to the organisation page and bump their access back to GM which would have fixed all of their project access.

**Comment by Mitchdoe** [comment]
That is what happened, the issue is that the GM was only on the Regional projects, bur the proponent added them as an editor to every project from the org. Say that the regional projects only made up 1/3 of the total organisation projects, even after bulk changing the access back to GM, he had a lot of projects to manually remove himself from.

**Comment by chrisala** [comment]
#595 will address this
