### ISSUE TITLE
Add link in MERIT API documentation to an editable view of sample activity forms

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/fieldcapture#52]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=564
*date:* Wed Feb  5 16:18:31 2014
*author:* CoolDa...@gmail.com
 ---

DoE requirement `#49`
Develop a user friendly API to guide grant recipients and grant managers to select the most appropriate activity for their project when building a plan

Comments - PB 6/2/14
Perhaps the lowest maintenance way of achieving this would be to create an "example" project which contains an example of every form. This would allow the example project and it's forms to be dynamically maintained in-sync with the models. The example project would need to:
 1) be Quarantined from other projects in the portal - from search, view, dashboard stats, etc.
 2) include context appropriate navigational links to/from other associated API documentation
 3) not save any data input by users into forms

**Comment by chrisala** [comment]
This is the demonstrator project.  Done.
