### ISSUE TITLE
Project Stage on an activity

### ISSUE THREAD

**Issue by Mitchdoe** [AtlasOfLivingAustralia/fieldcapture#529]
There is a project stage field at the top of an activity form preview, are we able to hide this until we have the stage configuration built? It currently always shows stage 1 and has been confusing to users.

**Comment by Mitchdoe** [comment]
Not just the preview, but also when reporting.

**Comment by chrisala** [comment]
Ive implemented something to: 
1) display the project stage correctly in the read-only and reporting view of an activity.
2) allow the project dates to be set via stage selection (or vice versa) on the planning view of the activity.
