### ISSUE TITLE
Usability improvements for audit tracking on projects

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/fieldcapture#54]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=566
*date:* Wed Feb  5 17:25:57 2014
*author:* CoolDa...@gmail.com
 ---

DoE requirement `#39`
Include audit/tracking function 

Comments - PB 6/2/14
The current audit feature is difficult to use and to hard to interpret what has been changed on a project between approval points. Gran managers are particularly keen for this feature to be enhanced.

Requirement details TBC, but starting with a better project search capability and a more visual way of seeing what was changed, would be a start.

**Comment by chrisala** [comment]
Done.
