### ISSUE TITLE
Ability to change blog entry order

### ISSUE THREAD

**Issue by Mitchdoe** [AtlasOfLivingAustralia/fieldcapture#560]
Promote / demote blog entries (site blog and project blog) via up & down arrows on the side. 
Currently ordered by order or creation, newest coming first. This should be the default, but would be good to have the ability to continually promote important stories while still creating other entries.

**Comment by chrisala** [comment]
Either this or the project progress summary would be useful

**Comment by chrisala** [comment]
Added a flag, "keep on top" to the edit page for a blog entry.  Entries with this flag set will always appear above entries without this flag.  Blog entries are sorted by this flag first, then date.

**Comment by chrisala** [comment]
Andy, does the "Keep on top" flag satisfy the requirement for projects to be able to present a progress summary?  #554

**Comment by Mitchdoe** [comment]
Chasing up, will get back to you with a reply when we hear back.
