### ISSUE TITLE
Service Provider link

### ISSUE THREAD

**Issue by Mitchdoe** [AtlasOfLivingAustralia/fieldcapture#589]
Can we add in a drop-down box to the Service Provider field in Project Settings tab, same as for Organisations in the field above it?
There seems to be a bug, in that if the Service Provider is updated, the hyperlink still takes you to the original SP organisation page.
Example: https://fieldcapture.ala.org.au/project/index/5894ae9c-5e39-419a-99be-44e5cc9690f9

**Comment by chrisala** [comment]
Agree, what is the priority?

**Comment by Mitchdoe** [comment]
How much work is involved? I can’t imagine this would be a problem for many projects, but it is an issue for affected proponents.

**Comment by chrisala** [comment]
Maybe 1/2 day
