### ISSUE TITLE
Can't display large view of photo point images 

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/fieldcapture#60]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=598
*date:* Sun Mar  2 14:45:57 2014
*author:* CoolDa...@gmail.com
 ---

Once photo point images are loaded they appear only as small thumbnails with no way of viewing them as a larger image.

Need to view these images (including attribution and description, which is not currently collected with the image), in a large format modal popup.

**Comment by chrisala** [comment]
Fixed.
