### ISSUE TITLE
Change MERI plan text

### ISSUE THREAD

**Issue by Mitchdoe** [AtlasOfLivingAustralia/fieldcapture#630]
Can we please change the text at the bottom of the Admin MERI plan page:
![image](https://cloud.githubusercontent.com/assets/15135599/14621398/d087b8c4-0605-11e6-9402-40fe8dd163d4.png) 

From: 
•	Your project is locked until it is approved by your case manager.
•	Once your plan is approved you can start editing MERI plan information.

To:
•	You will not be able to report activity data until your MERI plan has been approved by your case manager.

I think this message only appears once the plan has been submitted, but it should probably always be there?

**Comment by chrisala** [comment]
Before it's submitted it says something like "Build your project by adding MERI plan details, activities and project targets information"
After it's submitted it says the other message.  
If the second message is always shown, I presume we don't always want to show the first one as well?

**Comment by Mitchdoe** [comment]
Yes, we can remove that first message.
