### ISSUE TITLE
Implement different styling colours between DEV, TEST and PROD environments

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/fieldcapture#68]
_migrated from:_ https://code.google.com/p/ala/issues/detail?id=733
_date:_ Sat Jul  5 05:51:04 2014
_author:_ CoolDa...@gmail.com

---

With implementation of the Demonstrator project in the test environment, some users are finding it difficult to differentiate between the PROD and TEST environments. 

DoE has requested that we change the style colours in TEST to make it distinctly different from PROD.

**Comment by chrisala** [comment]
We have a banner now for different environments.
