### ISSUE TITLE
Support for multiple project funding sources

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/fieldcapture#70]
_migrated from:_ https://code.google.com/p/ala/issues/detail?id=735
_date:_ Sat Jul  5 06:10:04 2014
_author:_ CoolDa...@gmail.com

---

New doE programmes require projects to be apportioned across multiple funding streams. This is also a requirement of the generalised system as many projects undertaken by organisations involve multiple funding partners.

A simple multi-row table in the Admin>Project information tab should be adequate for this putpose.

**Comment by chrisala** [comment]
This has been implemented by BioCollect.
