### ISSUE TITLE
Ability to create a "mother/parent" project for regional delivery type projects

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/fieldcapture#72]
_migrated from:_ https://code.google.com/p/ala/issues/detail?id=737
_date:_ Sat Jul  5 21:07:43 2014
_author:_ CoolDa...@gmail.com

---

In cases such as regional delivery types of projects, DoE has requested the ability to create a 'mother/parent' project which allows proponents to report outcomes, issues and progress at a master project (head agreement) level.

A short-term work around for this would be to create a project shell within the existing design framework in which the only activities are reporting activities and which has links to each of the sub-projects in the 'project stories' section of the overview page. 

Ideally something more robust and specifically designed is probably desirable, but would need to consider implications around re-use of information in sub-projects for process stream-lining, dashboard and numeric data/metrics impacts, activity relationships and the consistency of schedules and aggregated data (eg. parent and sub-project costs, targets, etc.), the flow-on implications of add activities and data to both the parent and sub-projects, etc.

**Comment by chrisala** [comment]
Does the organisation page satisfy this requirement Peter?

**Comment by chrisala** [comment]
This is no longer a requirement.
