### ISSUE TITLE
Stage/year filters on dashboard

### ISSUE THREAD

**Issue by Mitchdoe** [AtlasOfLivingAustralia/fieldcapture#723]
Include filters on all dashboards that allow time selection. E.g. just activities delivered (activity end date) in 2015. Or even better, could break up by 6mths - Jan-June 2016.

**Comment by chrisala** [comment]
The output targets & announcements queries are done on projects, how do you want the date selection to work for projects?
Also, would you prefer date pickers to a fixed set of six month intervals/years?

**Comment by Mitchdoe** [comment]
Projects: Any project that has a start date on or after the specified "from" date and an end date on or before the specified "to" date.

How dynamic can this date filter be? Ideally, it would work like a calendar selection (i.e. pick any day), but would also work on 6 month blocks, e.g. your choosable options are Jan and July each year.
