### ISSUE TITLE
Ability to colour-code sites/dots on maps by selected attribute facets

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/fieldcapture#73]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=738
*date:* Sat Jul  5 21:30:40 2014
*author:* CoolDa...@gmail.com
 ---

DoE requirement

This request is for simple facet-based colouring of sites/dots on the fieldcapture home page map, similar to that provided on the ALA BIE records map. 

A specific case requested would be for differentiation between programmes displayed on the map, but there are also other attributes where colour differentiation would significantly add value to the mapped view. These are to be provided following further analysis.

**Comment by chrisala** [comment]
Done.
