### ISSUE TITLE
Retain activity header data entered after moving focus into output sections

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/fieldcapture#75]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=740
*date:* Sat Jul  5 21:47:37 2014
*author:* CoolDa...@gmail.com
 ---

MERIT user notified issue:

Whenever we edit some information in an Activity, it makes us re-enter the 'Actual Start' and 'Actual Finish' dates for that Activity before it will save the new information we have entered. Why aren't the Actual Start and Finish dates we've previously entered not retained like all other information we have entered?

Need to test!

**Comment by chrisala** [comment]
Can't reproduce.
