### ISSUE TITLE
Build a Site Management form for 20MT

### ISSUE THREAD

**Issue by Mitchdoe** [AtlasOfLivingAustralia/fieldcapture#807]
Needs to only be available for 20MT Service Providers tranche 1 and 2 sub-programs.

Title: Post revegetation site management

At the top it needs an "area managed" total field.

Then a nested table:
1st drop down menu (column):

• Mulching
• Watering
• Other

2nd column – Ha to be filled in for each activity. Note don't include a total at the bottom of this column (same problem as with site prep adding area).

Comments/ notes for each activity, with the following guidance (help text) – “Please advise what was done, why and by whom. Include quantities where relevant”.

Then we would need a revegetation table to capture In-fill planting, as well as a Pest management table and a Weed management table.

**Comment by Mitchdoe** [comment]
Additional changes.
1. Infill plantings table to mirror that in reveg form:
Species:  	No. Planted:   	Seed Sown (Kg):  	Type of stock   	Structural Layer   	Mature height   	Stock Provenance  	Cost / unit ($) 
Add a comments/notes box underneath this table.

2. Change the "area managed" field at the top of the page to "total area managed". This should not contribute to any output targets (it should still be mandatory).

3. Pull weed management up into the "Site Management Actions" table. It should be an option in the drop-down. This weed treatment is all follow-up and should not contribute to the weed output target.

4. Pest Management table to have a "Total treatment area (Ha)" field and a total "Type of treatment event" field above it. These figures should contribute to the pest management output target.
Add a comments/notes box underneath this table.

**Comment by chrisala** [comment]
Should the infill plantings data contribute to scoring/dashboard in the same was as the main revegetation form?
