### ISSUE TITLE
Grant manager not receiving stage report notification email

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/fieldcapture#81]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=746
*date:* Sat Jul  5 22:12:04 2014
*author:* CoolDa...@gmail.com
 ---

User submitted issue (via DoE `#127`):

Grant managers did not receive an email notifying that report for project Grant Id: X0000004479G had been submitted. 

Need to test!

**Comment by chrisala** [comment]
Fixed.
