### ISSUE TITLE
Ability to insert a javascript widget (youtube, vimeo, etc) link to display and play embedded videos on the Overview page

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/fieldcapture#83]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=748
*date:* Sun Jul  6 19:17:11 2014
*author:* CoolDa...@gmail.com
 ---

DoE want to have more effective ways for people to be able to tell stories about the outcomes of their projects. One important mechanism for doing this is with videos and they want the ability to attach both links to external video sources as well as to embed playable clips within the project overview page and also within a "Stories" tab on the home page of MERIT.

This should be added via the project ADMIN tab and should display on the project Overview tab within the column of published images on the LHS of the page.

Design of the "Stories" tab for the MERIT home page is still to be developed.

**Comment by chrisala** [comment]
This has been implemented.
