### ISSUE TITLE
Round off values of outputs (target and non-target) to integers only for display in dashboards 

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/fieldcapture#84]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=749
*date:* Mon Jul  7 18:57:11 2014
*author:* CoolDa...@gmail.com
 ---

Many numeric values for both target and non-target outputs are currently displaying in the dashboards with up to 10 decimal places. As aggregated values, it is only appropriate to display whole integer values in the dashboards.

**Comment by chrisala** [comment]
MERIT masters recommended 2 decimal places max.  This is now in dev.
