### ISSUE TITLE
Project data being overridden in activity sheets in project downloads

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#840]
Problem columns are description, start date, end date.

**Comment by Mitchdoe** [comment]
Found another problem here. When running the 25ALG - final report download, there is a field called "Organisation name" in reference to partner organisations. Instead though, the spreadsheet is just replicating the recipient organisation name in each row.

E.g. 4 entries in this activity: https://fieldcapture.ala.org.au/activity/index/602123e0-73f3-4bd2-b520-828b8c78d937?returnTo=https%3A%2F%2Ffieldcapture.ala.org.au%2Fproject%2Findex%2Ffb64d1cb-af1a-432d-bf18-a7b02e7bff92

![image](https://cloud.githubusercontent.com/assets/15135599/19504626/748caab0-9607-11e6-84ad-d2a1c0aa6551.png)


![image](https://cloud.githubusercontent.com/assets/15135599/19504613/627c4696-9607-11e6-808c-a561fd2bc81c.png)

Red should be blank and blue should be partner orgs.
