### ISSUE TITLE
NLP regional Outcome reporting

### ISSUE THREAD

**Issue by Mitchdoe** [AtlasOfLivingAustralia/fieldcapture#851]
Need a section on Activities tab for NLP Regional Funding projects that allows direct reporting against outcomes.

E.g. in the last stage of the project, we need a section to populate, maybe under the 'Planned Activities', with a 4 column table consisting of: the outcomes that they set in the MERI Plan; the assets these were associated with; a drop-down option against each of these: Have you completed this outcome (e.g. yes, no, partial); and then a text box where they can justify achievement and explain monitoring, etc.

**Comment by chrisala** [comment]
Is this covered by the new stage report?
