### ISSUE TITLE
Fieldcapture data feed to biocache

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/fieldcapture#88]
As discussed, one route for integrating these data is to copy the BVP model.
BVP exposes the following JSON web service which provides a list of projects that are suitable for harvesting:

http://volunteer.ala.org.au/ws/harvest

Each entry has a dataURL property which links to a darwin core headed CSV file. 

For every expedition a data resource is created in the collectory. The "expeditionHomePage" is treated as a unique GUID so we need something similar in MERIT land. I suggest we just use the project home page or the activity home page, which ever make the more sense.

We harvest from the BVP weekly so we can adopt the same model for MERIT, or do more frequent harvests if need be.

**Comment by chrisala** [comment]
This has been implemented by BioCollect.
