### ISSUE TITLE
Org report tab

### ISSUE THREAD

**Issue by Mitchdoe** [AtlasOfLivingAustralia/fieldcapture#880]
Changes needed for late March/early April.

Change 'Confirm' button to 'Finalise'.
No automatic email should be generated on selecting 'Finalise'.
Build a Self Assessment Moderation form that's only accessible to FC_ADMINs (possible) This form won't be used for every region, so we need to be able to create them as neded -This form needs to populate the regional response against each of the expectations, e.g. Yes/No against 1.1, 1.2, etc. Then it needs to have a column titled "Moderation" with a drop-down option of 'NA', 'Yes', 'No'. These should default to NA (no change required). Next column is a free text field for us to enter a reason.

The idea of this form is for the Department to adjust the scores provided by the region so that these moderated scores can be used to populate dashboards.

Behavior of dashboard.

If a "moderator" form hasn't been used, the dashboards should populate as they currently do; using the responses provided by the regions.
If a "moderator" form has been used, the dashboards should populate from these forms. Where the response is NA against an expectation, the dashboard should use the original response. Where the response has been modified for an expectation, the dashboard should use the updated response.

Where a score has been moderated can the dashboard have a * next to it? With a note below the dashboard that '*=Department moderated'.

**Comment by chrisala** [comment]
No longer required.
