### ISSUE TITLE
Make an "Annual stage report" form that includes the Outcome mapping option from the MERI plan.

### ISSUE THREAD

**Issue by Mitchdoe** [AtlasOfLivingAustralia/fieldcapture#954]
This would be applicable for all NLP Regional funding projects and would need to happen for the 30/6/17 stage.

**Comment by Mitchdoe** [comment]
Feedback:

1. Add a "lessons learned" mandatory field
2. Add an " Outline any deviations from the MERI plan which have affected delivery of activities." field
3. Update the help text on the outcome sections to indicate that the reply is intended for " Total progress against the outcome to date." (drop the reference to progress in this 12month period).

**Comment by chrisala** [comment]
1. Done.  Please provide feedback on wording.
2. Isn't this already there?  Can you please let me know what changes are required to the existing field?
3. Done.

**Comment by Mitchdoe** [comment]
Sorry, 2 was there already. It all looks good, but can you please switch around the WH&S and the Lessons Learned fields?

Also, can lessons learned help text please be updated to: Description of lessons learnt from the project and how they may be applied in the future.

**Comment by chrisala** [comment]
Updated.
