### ISSUE TITLE
Allow activities to be added in plan submitted/approved phases.

### ISSUE THREAD

**Issue by Mitchdoe** [AtlasOfLivingAustralia/fieldcapture#989]
Activities should be able to be added regardless of the MERI plan phase.
However, activities should still only be able to be changed (e.g. type, theme, dates, stage, etc.) or deleted when in the planning phase.
Also, activities cannot be allowed to be added to a stage that is in the submitted/published state.

**Comment by chrisala** [comment]
This is no longer wanted.
