### ISSUE TITLE
Ability to rotate photos

### ISSUE THREAD

**Issue by Mitchdoe** [AtlasOfLivingAustralia/fieldcapture#996]

**Comment by chrisala** [comment]
Can you please clarify what is wanted for this one?  Is there an example where a photo orientation is incorrect?

**Comment by Mitchdoe** [comment]
Hi Chris, E.g. photopoints on this project: https://fieldcapture.ala.org.au/project/index/f8b75249-f0cb-4a36-9649-30a01528ea78

Not incorrect, but they're getting automatically rotated to best fit by the look of it (short sides vertically and long sides horizontally). Some are even going upside-down though:
![image](https://cloud.githubusercontent.com/assets/15135599/23592196/68f12bac-0251-11e7-9ea6-afb555bf3f37.png)

**Comment by chrisala** [comment]
Thanks Mitch,
This is happening because browsers don't automatically orient images based on the exif orientation metadata and MERIT isn't doing anything to check that field and perform the rotation.

**Comment by Mitchdoe** [comment]
Is it possible to add in a “rotate” button? It would need to save the new orientation?

**Comment by chrisala** [comment]
It would be better to do it automatically I think.

**Comment by Mitchdoe** [comment]
Yep, that sounds even better!
